### ISSUE TITLE
Cannot find clusters/4.6-staticIPs directory

### ISSUE THREAD

**Issue by pichuang** [IronicBadger/ocp4#16]
There are no 4.6-staticIPs direcitry in clusters, only 4.5-staticIPs.

**Comment by ironicbadger** [comment]
Where did you find the reference to that string? I changed the names of the clusters and obviously missed a reference somewhere.

**Comment by tomsherrod** [comment]
makefile
tfinit:
	cd clusters/4.5; terraform init
	cd clusters/4.5-staticIPs; terraform init
	cd clusters/4.6-staticIPs; terraform init
and the README

**Comment by ironicbadger** [comment]
I've just pushed an update that fixes quite a few things, reopen this please if this issue persists.
