### ISSUE TITLE
Static IP setting cannot be set

### ISSUE THREAD

**Issue by garethhk** [IronicBadger/ocp4#17]
IP cannot change using Afterburn, Do i need a  OPNsense for OCP 4.6.1?

My vCenter is behind my physical router, and the router have DHCP function, it provided 172.29.1.XX subnet.

I used almost all the same config of the resource, the only config changes are the vCenter stuffs

after the terraform apply, all node still use the ip 172.29.1.XX, as so, the OCP cluster cannot start up.

- Using previously-installed community-terraform-providers/ignition v2.1.1
- Using previously-installed terraform-providers/ignition v1.2.1
- Using previously-installed hashicorp/vsphere v1.24.2

==============install-config.yaml============================
'''
apiVersion: v1
baseDomain: openshift.lab.int
compute:
- hyperthreading: Enabled
  name: worker
  replicas: 0
controlPlane:
  hyperthreading: Enabled
  name: master
  replicas: 3
metadata:
  name: ocp46
platform:
  vsphere:
    vcenter: 172.29.1.206
    username: administrator@vsphere.local
    password: ''
    datacenter: myDatacenter
    defaultDatastore: myDatastore
fips: false 
pullSecret: '{"auths":{
sshKey: 'ssh-rsa

==============4.6/terraform.tfvars==============================
## Node IPs
loadbalancer_ip = "192.168.5.160"
coredns_ip = "192.168.5.169"
bootstrap_ip = "192.168.5.168"
master_ips = ["192.168.5.161", "192.168.5.162", "192.168.5.163"]
worker_ips = ["192.168.5.164", "192.168.5.165"]
#worker_ips = ["192.168.5.164", "192.168.5.165", "192.168.5.166"]

## Cluster configuration
rhcos_template = "rhcos-4.6.1"
cluster_slug = "ocp46"
cluster_domain = "openshift.lab.int"
machine_cidr = "192.168.5.0/16"
netmask ="255.255.0.0"

## DNS
local_dns = "192.168.5.169" # probably the same as coredns_ip
#public_dns = "192.168.1.254" # e.g. 1.1.1.1
#gateway = "192.168.1.254"
#public_dns = "192.168.1.1" # e.g. 1.1.1.1
#gateway = "192.168.1.1"
public_dns = "172.29.1.1" # e.g. 1.1.1.1
gateway = "172.29.1.1"

## probably via generate-configs.sh
bootstrap_ignition_path = "../../openshift/bootstrap.ign"
master_ignition_path = "../../openshift/master.ign"
worker_ignition_path = "../../openshift/worker.ign"
'''
===========4.6/variables.tf====================
'''
###########################
## OCP Cluster Vars

variable "cluster_slug" {
  type = string
}

variable "bootstrap_complete" {
  type    = string
  default = "false"
}
################
## VMware vars - unlikely to need to change between releases of OCP

variable "rhcos_template" {
  type = string
}

provider "vsphere" {
  user           = yamldecode(file("~/.config/ocp/vsphere.yaml"))["vsphere-user"]
  password       = yamldecode(file("~/.config/ocp/vsphere.yaml"))["vsphere-password"]
  vsphere_server = yamldecode(file("~/.config/ocp/vsphere.yaml"))["vsphere-server"]

  # If you have a self-signed cert
  allow_unverified_ssl = true
}

data "vsphere_datacenter" "dc" {
  name = yamldecode(file("~/.config/ocp/vsphere.yaml"))["vsphere-dc"]
}

data "vsphere_compute_cluster" "cluster" {
  name          = yamldecode(file("~/.config/ocp/vsphere.yaml"))["vsphere-cluster"]
  datacenter_id = data.vsphere_datacenter.dc.id
}

data "vsphere_network" "network" {
  name          = "VM Network"
  datacenter_id = data.vsphere_datacenter.dc.id
}

data "vsphere_datastore" "nvme500" {
...
..
.
'''
=================ocp4/modules/rhcos-static/main.tf===============================
'''
locals {
  ignition_encoded = "data:text/plain;charset=utf-8;base64,${base64encode(var.ignition)}"
}

data "ignition_file" "hostname" {

  path = "/etc/hostname"
  mode = "775"

  content {
    content = var.name
  }
}

data "ignition_config" "vm" {

  merge {
    source = local.ignition_encoded
  }
  files = [
    data.ignition_file.hostname.rendered
  ]
}

resource "vsphere_virtual_machine" "vm" {

  name               = var.name
  resource_pool_id   = var.resource_pool_id
  datastore_id       = var.datastore
  num_cpus           = var.num_cpu
  memory             = var.memory
  memory_reservation = var.memory
  guest_id           = var.guest_id
  folder             = var.folder
  enable_disk_uuid   = "true"

  wait_for_guest_net_timeout  = "0"
  wait_for_guest_net_routable = "false"

  network_interface {
    network_id   = var.network
    adapter_type = var.adapter_type
  }

  disk {
    label            = "disk0"
    size             = var.disk_size
    thin_provisioned = var.thin_provisioned
  }

  clone {
    template_uuid = var.template
  }

  extra_config = {
    "guestinfo.ignition.config.data"          = base64encode(data.ignition_config.vm.rendered)
    "guestinfo.ignition.config.data.encoding" = "base64"

    # configures the static IP
    # https://www.man7.org/linux/man-pages/man7/dracut.cmdline.7.html
    "guestinfo.afterburn.initrd.network-kargs" = "ip=${var.ipv4_address}::${var.gateway}:${var.netmask}:${var.name}:ens192:off:${var.dns_address}"
  }
}
'''
=======================make 46 output=======================================
'''
[root@localhost ocp4]# make 46
./generate-configs.sh
INFO Consuming Install Config from target directory
WARNING Making control-plane schedulable by setting MastersSchedulable to true for Scheduler cluster settings
INFO Manifests created in: manifests and openshift
INFO Consuming Master Machines from target directory
INFO Consuming OpenShift Install (Manifests) from target directory
INFO Consuming Worker Machines from target directory
INFO Consuming Openshift Manifests from target directory
INFO Consuming Common Manifests from target directory
INFO Ignition-Configs created in: . and auth
cd clusters/4.6; terraform apply -auto-approve
module.bootstrap[0].data.ignition_file.hostname: Refreshing state...
module.dns_vm[0].data.ignition_file.hostname: Refreshing state...
module.coredns.data.ignition_file.openshift_lab_db: Refreshing state...
module.worker[1].data.ignition_file.hostname: Refreshing state...
module.lb.data.ignition_systemd_unit.haproxy: Refreshing state...
module.lb.data.ignition_user.core: Refreshing state...
module.lb_vm[0].data.ignition_file.hostname: Refreshing state...
module.lb.data.ignition_file.haproxy: Refreshing state...
module.master[2].data.ignition_file.hostname: Refreshing state...
module.coredns.data.ignition_file.corefile: Refreshing state...
module.coredns.data.ignition_user.core: Refreshing state...
module.coredns.data.ignition_systemd_unit.coredns: Refreshing state...
module.master[0].data.ignition_file.hostname: Refreshing state...
module.worker[0].data.ignition_file.hostname: Refreshing state...
module.master[1].data.ignition_file.hostname: Refreshing state...
module.lb.data.ignition_config.lb: Refreshing state...
module.bootstrap[0].data.ignition_config.vm: Refreshing state...
module.worker[1].data.ignition_config.vm: Refreshing state...
module.worker[0].data.ignition_config.vm: Refreshing state...
module.coredns.data.ignition_config.coredns: Refreshing state...
module.master[2].data.ignition_config.vm: Refreshing state...
module.master[0].data.ignition_config.vm: Refreshing state...
module.master[1].data.ignition_config.vm: Refreshing state...
module.lb_vm[0].data.ignition_config.vm: Refreshing state...
module.dns_vm[0].data.ignition_config.vm: Refreshing state...
data.vsphere_datacenter.dc: Refreshing state...
data.vsphere_datastore.nvme500: Refreshing state...
data.vsphere_virtual_machine.template: Refreshing state...
data.vsphere_datastore.spc500: Refreshing state...
data.vsphere_network.network: Refreshing state...
data.vsphere_datastore.mx1tb: Refreshing state...
data.vsphere_compute_cluster.cluster: Refreshing state...
module.master[1].vsphere_virtual_machine.vm: Creating...
module.master[0].vsphere_virtual_machine.vm: Creating...
module.worker[0].vsphere_virtual_machine.vm: Creating...
module.lb_vm[0].vsphere_virtual_machine.vm: Creating...
module.master[2].vsphere_virtual_machine.vm: Creating...
module.dns_vm[0].vsphere_virtual_machine.vm: Creating...
module.worker[1].vsphere_virtual_machine.vm: Creating...
module.bootstrap[0].vsphere_virtual_machine.vm: Creating...
module.master[1].vsphere_virtual_machine.vm: Still creating... [10s elapsed]
module.master[0].vsphere_virtual_machine.vm: Still creating... [10s elapsed]
module.worker[0].vsphere_virtual_machine.vm: Still creating... [10s elapsed]
module.lb_vm[0].vsphere_virtual_machine.vm: Still creating... [10s elapsed]
module.master[2].vsphere_virtual_machine.vm: Still creating... [10s elapsed]
module.dns_vm[0].vsphere_virtual_machine.vm: Still creating... [10s elapsed]
module.worker[1].vsphere_virtual_machine.vm: Still creating... [10s elapsed]
module.bootstrap[0].vsphere_virtual_machine.vm: Still creating... [10s elapsed]
module.master[1].vsphere_virtual_machine.vm: Still creating... [20s elapsed]
module.master[0].vsphere_virtual_machine.vm: Still creating... [20s elapsed]
module.worker[0].vsphere_virtual_machine.vm: Still creating... [20s elapsed]
module.lb_vm[0].vsphere_virtual_machine.vm: Still creating... [20s elapsed]
module.dns_vm[0].vsphere_virtual_machine.vm: Still creating... [20s elapsed]
module.master[2].vsphere_virtual_machine.vm: Still creating... [20s elapsed]
module.worker[1].vsphere_virtual_machine.vm: Still creating... [20s elapsed]
module.bootstrap[0].vsphere_virtual_machine.vm: Still creating... [20s elapsed]
module.master[1].vsphere_virtual_machine.vm: Still creating... [30s elapsed]
module.master[0].vsphere_virtual_machine.vm: Still creating... [30s elapsed]
module.worker[0].vsphere_virtual_machine.vm: Still creating... [30s elapsed]
module.lb_vm[0].vsphere_virtual_machine.vm: Still creating... [30s elapsed]
module.master[2].vsphere_virtual_machine.vm: Still creating... [30s elapsed]
module.dns_vm[0].vsphere_virtual_machine.vm: Still creating... [30s elapsed]
module.worker[1].vsphere_virtual_machine.vm: Still creating... [30s elapsed]
module.bootstrap[0].vsphere_virtual_machine.vm: Still creating... [30s elapsed]
module.master[1].vsphere_virtual_machine.vm: Still creating... [40s elapsed]
module.master[0].vsphere_virtual_machine.vm: Still creating... [40s elapsed]
module.worker[0].vsphere_virtual_machine.vm: Still creating... [40s elapsed]
module.lb_vm[0].vsphere_virtual_machine.vm: Still creating... [40s elapsed]
module.master[2].vsphere_virtual_machine.vm: Still creating... [40s elapsed]
module.dns_vm[0].vsphere_virtual_machine.vm: Still creating... [40s elapsed]
module.worker[1].vsphere_virtual_machine.vm: Still creating... [40s elapsed]
module.bootstrap[0].vsphere_virtual_machine.vm: Still creating... [40s elapsed]
module.master[1].vsphere_virtual_machine.vm: Still creating... [50s elapsed]
module.master[0].vsphere_virtual_machine.vm: Still creating... [50s elapsed]
module.worker[0].vsphere_virtual_machine.vm: Still creating... [50s elapsed]
module.lb_vm[0].vsphere_virtual_machine.vm: Still creating... [50s elapsed]
module.dns_vm[0].vsphere_virtual_machine.vm: Still creating... [50s elapsed]
module.master[2].vsphere_virtual_machine.vm: Still creating... [50s elapsed]
module.worker[1].vsphere_virtual_machine.vm: Still creating... [50s elapsed]
module.bootstrap[0].vsphere_virtual_machine.vm: Still creating... [50s elapsed]
module.master[1].vsphere_virtual_machine.vm: Still creating... [1m0s elapsed]
module.master[0].vsphere_virtual_machine.vm: Still creating... [1m0s elapsed]
module.worker[0].vsphere_virtual_machine.vm: Still creating... [1m0s elapsed]
module.lb_vm[0].vsphere_virtual_machine.vm: Still creating... [1m0s elapsed]
module.master[2].vsphere_virtual_machine.vm: Still creating... [1m0s elapsed]
module.dns_vm[0].vsphere_virtual_machine.vm: Still creating... [1m0s elapsed]
module.worker[1].vsphere_virtual_machine.vm: Still creating... [1m0s elapsed]
module.bootstrap[0].vsphere_virtual_machine.vm: Still creating... [1m0s elapsed]
module.master[1].vsphere_virtual_machine.vm: Still creating... [1m10s elapsed]
module.master[0].vsphere_virtual_machine.vm: Still creating... [1m10s elapsed]
module.worker[0].vsphere_virtual_machine.vm: Still creating... [1m10s elapsed]
module.lb_vm[0].vsphere_virtual_machine.vm: Still creating... [1m10s elapsed]
module.dns_vm[0].vsphere_virtual_machine.vm: Still creating... [1m10s elapsed]
module.master[2].vsphere_virtual_machine.vm: Still creating... [1m10s elapsed]
module.worker[1].vsphere_virtual_machine.vm: Still creating... [1m10s elapsed]
module.bootstrap[0].vsphere_virtual_machine.vm: Still creating... [1m10s elapsed]
module.worker[0].vsphere_virtual_machine.vm: Creation complete after 1m16s [id=42196866-972c-a82d-c19e-c090af927089]
module.master[1].vsphere_virtual_machine.vm: Still creating... [1m20s elapsed]
module.master[0].vsphere_virtual_machine.vm: Still creating... [1m20s elapsed]
module.lb_vm[0].vsphere_virtual_machine.vm: Still creating... [1m20s elapsed]
module.master[2].vsphere_virtual_machine.vm: Still creating... [1m20s elapsed]
module.dns_vm[0].vsphere_virtual_machine.vm: Still creating... [1m20s elapsed]
module.worker[1].vsphere_virtual_machine.vm: Still creating... [1m20s elapsed]
module.bootstrap[0].vsphere_virtual_machine.vm: Still creating... [1m20s elapsed]
module.dns_vm[0].vsphere_virtual_machine.vm: Creation complete after 1m20s [id=4219f36d-de4e-68b2-170a-90d7144c1cc4]
module.master[2].vsphere_virtual_machine.vm: Creation complete after 1m20s [id=4219bc8a-4d3a-3ef6-a80d-3fa2b3a376d8]
module.master[1].vsphere_virtual_machine.vm: Creation complete after 1m21s [id=4219bfc8-57d3-abed-201d-f5f53a0a5e58]
module.lb_vm[0].vsphere_virtual_machine.vm: Creation complete after 1m20s [id=421941d6-6d38-4fff-3f89-20e8048eff6a]
module.master[0].vsphere_virtual_machine.vm: Creation complete after 1m23s [id=42199085-d992-47b9-5f48-3ec52cbe2004]
module.worker[1].vsphere_virtual_machine.vm: Creation complete after 1m22s [id=421997b6-0ea2-78c6-baec-85e6085e59d0]
module.bootstrap[0].vsphere_virtual_machine.vm: Creation complete after 1m23s [id=4219c703-c669-4604-e0b6-c3be5da0fca0]

Warning: Interpolation-only expressions are deprecated

  on main.tf line 10, in module "master":
  10:   folder    = "${var.cluster_slug}"

Terraform 0.11 and earlier required all non-constant expressions to be
provided via interpolation syntax, but this pattern is now deprecated. To
silence this warning, remove the "${ sequence from the start and the }"
sequence from the end of this expression, leaving just the inner expression.

Template interpolation syntax is still used to construct strings from
expressions when the template includes multiple interpolation sequences or a
mixture of literal strings and interpolations. This deprecation applies only
to templates that consist entirely of a single interpolation sequence.

(and 5 more similar warnings elsewhere)

Apply complete! Resources: 8 added, 0 changed, 0 destroyed.
'''

**Comment by ironicbadger** [comment]
I've just pushed an update that fixes quite a few things, reopen this please if this issue persists.
