### ISSUE TITLE
Terraform Apply invalid configuration

### ISSUE THREAD

**Issue by jguevara-assist** [IronicBadger/ocp4#18]
When launching the Terraform apply command, the following error is generated:

Error: invalid configuration:
error at $.contents: invalid unit content: unexpected newline encountered while parsing option name

  on ../../modules/ignition_coredns/main.tf line 6, in data "ignition_systemd_unit" "coredns":
   6: data "ignition_systemd_unit" "coredns" {

Error: invalid configuration:
error at $.contents: invalid unit content: unexpected newline encountered while parsing option name

  on ../../modules/ignition_haproxy/main.tf line 1, in data "ignition_systemd_unit" "haproxy":
   1: data "ignition_systemd_unit" "haproxy" {

**Comment by ironicbadger** [comment]
I've just pushed an update that fixes quite a few things, reopen this please if this issue persists.

**Comment by nicolasni1977** [comment]
the issue still persists


Error: invalid configuration:
error at $.contents: invalid unit content: unexpected newline encountered while parsing option name


  on ..\..\modules\ignition_coredns\main.tf line 6, in data "ignition_systemd_unit" "coredns":
   6: data "ignition_systemd_unit" "coredns" {



Error: invalid configuration:
error at $.contents: invalid unit content: unexpected newline encountered while parsing option name


  on ..\..\modules\ignition_haproxy\main.tf line 1, in data "ignition_systemd_unit" "haproxy":
   1: data "ignition_systemd_unit" "haproxy" {

**Comment by ironicbadger** [comment]
What's your terraform version?

**Comment by nicolasni1977** [comment]
Terraform version: 0.14.5 -- Terraform version

[Service]
TimeoutStartSec=0
ExecStartPre=-/bin/podman kill coredns
ExecStartPre=-/bin/podman rm coredns
ExecStartPre=/bin/podman pull quay.io/openshift/origin-coredns
ExecStart=/bin/podman run --name coredns \
  --net=host \
  --privileged \
  -v /opt/coredns/:/root/:Z \
  quay.io/openshift/origin-coredns -conf /root/Corefile

the code has "\", I removed them all, it works, same for the haproxy..

**Comment by ironicbadger** [comment]
Perhaps you could help me in reproducing, I've been using the repo just this week and made some updates and don't experience the issues you seem to be.

I'm using vscode and wondering if it's an editor issue? Line endings? Or something? See:

- https://github.com/hashicorp/terraform-provider-ignition/issues/41

I don't see any "" as you suggest in the template files either.

https://github.com/IronicBadger/ocp4/blob/master/modules/ignition_coredns/files/coredns.service

**Comment by nicolasni1977** [comment]
"ExecStart=/bin/podman run --name coredns \
  --net=host \
  --privileged \
  -v /opt/coredns/:/root/:Z \"

what I meant, I removed the "\" in all lines, after that, it works

**Comment by ironicbadger** [comment]
Is this in the rendered output?

**Comment by nicolasni1977** [comment]
yup I think so

**Comment by ironicbadger** [comment]
Sorry but I can't replicate. This is service file as it deployed onto a fresh 4.7 node for coredns.

```
[core@ocp47-coredns ~]$ cat /etc/systemd/system/coredns.service
[Unit]
Description=coredns
After=network-online.target
Wants=network-online.target

[Service]
TimeoutStartSec=0
ExecStartPre=-/bin/podman kill coredns
ExecStartPre=-/bin/podman rm coredns
ExecStartPre=/bin/podman pull quay.io/openshift/origin-coredns
ExecStart=/bin/podman run --name coredns \
  --net=host \
  --privileged \
  -v /opt/coredns/:/root/:Z \
  quay.io/openshift/origin-coredns -conf /root/Corefile

[Install]
WantedBy=multi-user.target
```
