### ISSUE TITLE
Not able to resolve DNS using coredns - even from coredns server directly

### ISSUE THREAD

**Issue by nicolasni1977** [IronicBadger/ocp4#22]
[core@ocp46-coredns ~]$ dig lb.ocp46.openshift.ako.test @10.206.43.254

; <<>> DiG 9.11.13-RedHat-9.11.13-6.el8_2.1 <<>> lb.ocp46.openshift.ako.test @10.206.43.254
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 42931
;; flags: qr rd ra ad; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;lb.ocp46.openshift.ako.test.   IN      A

;; AUTHORITY SECTION:
.                       86385   IN      SOA     a.root-servers.net. nstld.verisign-grs.com. 2021051300 1800 900 604800 86400

;; Query time: 40 msec
;; SERVER: 10.206.43.254#53(10.206.43.254)
;; WHEN: Thu May 13 13:58:40 UTC 2021
;; MSG SIZE  rcvd: 131

**Comment by ironicbadger** [comment]
You'll need to modify the files under `modules/ignition_coredns/files` to reflect your domain - what's there is hard coded in a few places to `openshift.lab.int`. I should probably fix that but then again this repo is meant to be a starting point, not the finished article :)
